# 1. 미국회사_파산데이터_1 을 활용하여 다음을 구현하시오.  50점

# 1.1 summary 함수를 만들고 그 결과를 나타내시오

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# 1) 데이터프레임의 Shape을 구현

In [3]:
summary = pd.read_csv('C:/Users/user/Documents/하계계절학기/Untitled Folder/기말고사/미국회사_파산데이터_1.csv', 
                       encoding = 'cp949', engine = 'python')
summary.head()

,company_name,status_label,year,유동자산,매출원가,통화가치절하,세전영업 현금흐름,재고,순이익,총채권,...,순매출액,총자산,장기부채,금리,매출총이익,총유동부채,잉여금,총매출,총부채,총운용비용
0,C_1,alive,1999,511.267,833.107,18.373,89.031,336.018,35.163,128.348,...,1024.333,740.998,180.447,70.658,191.226,163.816,201.026,1024.333,401.483,935.302
1,C_1,alive,2000,485.856,713.811,18.577,64.367,320.590,18.531,115.187,...,874.255,701.854,179.987,45.790,160.444,125.392,204.065,874.255,361.642,809.888
2,C_1,alive,2001,436.656,526.477,22.496,27.207,286.588,-58.939,77.528,...,638.721,710.199,217.699,4.711,112.244,150.464,139.603,638.721,399.964,611.514
3,C_1,alive,2002,396.412,496.747,27.172,30.745,259.954,-12.410,66.322,...,606.337,686.621,164.658,3.573,109.590,203.575,124.106,606.337,391.633,575.592
4,C_1,alive,2003,432.204,523.302,26.680,47.491,247.245,3.504,104.661,...,651.958,709.292,248.666,20.811,128.656,131.261,131.884,651.958,407.608,604.467

In [4]:
summary.shape

(30751, 21)

In [5]:
# 2) summ = pd.DataFrame(df.dtypes, columns=['data type'])을 사용하여 summary 데이터 프레임을 만들어라

In [6]:
summ = pd.DataFrame(summary.dtypes, columns = ['data type'])
summ

             data type
company_name    object
status_label    object
year             int64
유동자산           float64
매출원가           float64
통화가치절하         float64
세전영업 현금흐름      float64
재고             float64
순이익            float64
총채권            float64
시장가치           float64
순매출액           float64
총자산            float64
장기부채           float64
금리             float64
매출총이익          float64
총유동부채          float64
잉여금            float64
총매출            float64
총부채            float64
총운용비용          float64

In [7]:
# 3) 결측치 (#missing)

In [8]:
missing_values = summary.isnull().sum()
summ = pd.DataFrame(missing_values, columns = ['#missing'])
summ

              #missing
company_name         0
status_label         0
year                 0
유동자산                 0
매출원가                 0
통화가치절하               0
세전영업 현금흐름            0
재고                   0
순이익                  0
총채권                  0
시장가치                 0
순매출액                 0
총자산                  0
장기부채                 0
금리                   0
매출총이익                0
총유동부채                0
잉여금                  0
총매출                  0
총부채                  0
총운용비용                0

In [9]:
# 4) 결측치 비율 (%missing)

In [10]:
missing_percentage = (summary.isnull().mean()) * 100
summ = pd.DataFrame(missing_percentage, columns = ['%missing'])
summ

              %missing
company_name       0.0
status_label       0.0
year               0.0
유동자산               0.0
매출원가               0.0
통화가치절하             0.0
세전영업 현금흐름          0.0
재고                 0.0
순이익                0.0
총채권                0.0
시장가치               0.0
순매출액               0.0
총자산                0.0
장기부채               0.0
금리                 0.0
매출총이익              0.0
총유동부채              0.0
잉여금                0.0
총매출                0.0
총부채                0.0
총운용비용              0.0

In [11]:
# 3) summ[‘min’], summ[‘max’]를 컬럼으로 표현하시오  
# 4) 구현된 함수를 실행함으로서 데이터 summary를 나타내시오.

In [14]:
df = summary.describe(include = 'all').transpose()

summ['min'] = df['min']
summ['max'] = df['max']

summ['first value'] = df.loc[:, '25%']
summ['second value'] = df.loc[:, '50%']
summ['third value'] = df.loc[:, '75%']

summ

,%missing,min,max,first value,second value,third value
company_name,0.0,NaN,NaN,NaN,NaN,NaN
status_label,0.0,NaN,NaN,NaN,NaN,NaN
year,0.0,1999.0,2018.0,2002.0,2006.0,2012.0
유동자산,0.0,-0.013,169662.0,25.7265,184.7,921.5375
매출원가,0.0,-1.477,374623.0,30.5405,255.695,1485.172
통화가치절하,0.0,0.0,28430.0,1.814,16.955,101.961
세전영업 현금흐름,0.0,-21913.0,81730.0,1.828,44.063,336.5235
재고,0.0,0.0,62567.0,1.7935,27.049,198.015
순이익,0.0,-29580.0,104821.0,-1.512,7.982,106.038
총채권,0.0,0.0,65812.0,5.972,49.907,300.895
시장가치,0.0,0.0001,1073390.54,43.1702,386.2468,2509.0363
순매출액,0.0,-1964.999,511729.0,49.5115,421.084,2367.803
총자산,0.0,0.001,531864.0,54.4135,432.774,2719.123
장기부채,0.0,-0.023,166250.0,0.355,37.791,594.7185
금리,0.0,-25913.0,71230.0,0.048,22.671,218.6
매출총이익,0.0,-21536.0,137106.0,15.3735,129.808,745.059
총유동부채,0.0,0.001,116866.0,12.2055,81.961,529.5675
잉여금,0.0,-78525.0,402089.0,-16.3065,42.252,545.6345
총매출,0.0,-1964.999,511729.0,49.5115,421.084,2367.803
총부채,0.0,0.001,337980.0,21.363,195.09,1595.743
총운용비용,0.0,0.009,481580.0,48.721,357.373,1959.033

# 1.2 Correlation matrix를 구현하시오.

In [15]:
correlation_matrix = summary.corr()
correlation_matrix

,year,유동자산,매출원가,통화가치절하,세전영업 현금흐름,재고,순이익,총채권,시장가치,순매출액,총자산,장기부채,금리,매출총이익,총유동부채,잉여금,총매출,총부채,총운용비용
year,1.000000,0.119715,0.081445,0.103207,0.104533,0.090848,0.081339,0.100092,0.097405,0.093596,0.130852,0.152844,0.095879,0.104862,0.108220,0.082869,0.093596,0.135781,0.087266
유동자산,0.119715,1.000000,0.668161,0.655875,0.810610,0.641576,0.712035,0.856881,0.822072,0.759086,0.824440,0.664650,0.807099,0.832568,0.916201,0.576463,0.759086,0.807622,0.715018
매출원가,0.081445,0.668161,1.000000,0.612320,0.692324,0.781058,0.578254,0.664429,0.589424,0.977453,0.692132,0.485321,0.666363,0.744509,0.785733,0.651465,0.977453,0.660260,0.989495
통화가치절하,0.103207,0.655875,0.612320,1.000000,0.858087,0.417097,0.600032,0.703278,0.680817,0.705465,0.915426,0.789030,0.719766,0.794029,0.751329,0.638453,0.705465,0.879967,0.644011
세전영업 현금흐름,0.104533,0.810610,0.692324,0.858087,1.000000,0.504645,0.827965,0.785137,0.883489,0.805691,0.920249,0.738292,0.974105,0.923235,0.841762,0.716948,0.805691,0.870552,0.731592
재고,0.090848,0.641576,0.781058,0.417097,0.504645,1.000000,0.425684,0.491049,0.492754,0.787699,0.547193,0.407856,0.498593,0.658181,0.711573,0.465414,0.787699,0.545515,0.807830
순이익,0.081339,0.712035,0.578254,0.600032,0.827965,0.425684,1.000000,0.646841,0.793212,0.667953,0.716399,0.497197,0.855149,0.755344,0.706441,0.672995,0.667953,0.656282,0.606733
총채권,0.100092,0.856881,0.664429,0.703278,0.785137,0.491049,0.646841,1.000000,0.706935,0.724592,0.809619,0.659103,0.751790,0.732261,0.878140,0.618875,0.724592,0.813741,0.680303
시장가치,0.097405,0.822072,0.589424,0.680817,0.883489,0.492754,0.793212,0.706935,1.000000,0.708786,0.809289,0.612300,0.894643,0.858244,0.787236,0.686766,0.708786,0.744304,0.642863
순매출액,0.093596,0.759086,0.977453,0.705465,0.805691,0.787699,0.667953,0.724592,0.708786,1.000000,0.789877,0.588095,0.778615,0.868690,0.856673,0.688106,1.000000,0.754405,0.993258
총자산,0.130852,0.824440,0.692132,0.915426,0.920249,0.547193,0.716399,0.809619,0.809289,0.789877,1.000000,0.867075,0.841042,0.873684,0.890934,0.690625,0.789877,0.972349,0.728999
장기부채,0.152844,0.664650,0.485321,0.789030,0.738292,0.407856,0.497197,0.659103,0.612300,0.588095,0.867075,1.000000,0.650703,0.720872,0.731945,0.372160,0.588095,0.925557,0.532371
금리,0.095879,0.807099,0.666363,0.719766,0.974105,0.498593,0.855149,0.751790,0.894643,0.778615,0.841042,0.650703,1.000000,0.898530,0.807186,0.688147,0.778615,0.789469,0.705497
매출총이익,0.104862,0.832568,0.744509,0.794029,0.923235,0.658181,0.755344,0.732261,0.858244,0.868690,0.873684,0.720872,0.898530,1.000000,0.865292,0.647312,0.868690,0.836301,0.819124
총유동부채,0.108220,0.916201,0.785733,0.751329,0.841762,0.711573,0.706441,0.878140,0.787236,0.856673,0.890934,0.731945,0.807186,0.865292,1.000000,0.634033,0.856673,0.899256,0.821237
잉여금,0.082869,0.576463,0.651465,0.638453,0.716948,0.465414,0.672995,0.618875,0.686766,0.688106,0.690625,0.372160,0.688147,0.647312,0.634033,1.000000,0.688106,0.586662,0.651654
총매출,0.093596,0.759086,0.977453,0.705465,0.805691,0.787699,0.667953,0.724592,0.708786,1.000000,0.789877,0.588095,0.778615,0.868690,0.856673,0.688106,1.000000,0.754405,0.993258
총부채,0.135781,0.807622,0.660260,0.879967,0.870552,0.545515,0.656282,0.813741,0.744304,0.754405,0.972349,0.925557,0.789469,0.836301,0.899256,0.586662,0.754405,1.000000,0.697899
총운용비용,0.087266,0.715018,0.989495,0.644011,0.731592,0.807830,0.606733,0.680303,0.642863,0.993258,0.728999,0.532371,0.705497,0.819124,0.821237,0.651654,0.993258,0.697899,1.000000

# 1.3 파산한 회사 중에서 시장가치가 가장 크고 순이익이 가장 높은 회사를 찾아서 10개를 표시하시오

In [21]:
pd.set_option('display.max_columns', None)
sorted_companies = summary.sort_values(by = ['시장가치', '순이익'], ascending = False)
top_10 = sorted_companies.head(10)
top_10

,company_name,status_label,year,유동자산,매출원가,통화가치절하,세전영업 현금흐름,재고,순이익,총채권,시장가치,순매출액,총자산,장기부채,금리,매출총이익,총유동부채,잉여금,총매출,총부채,총운용비용
7800,C_644,alive,2009,59247.0,96853.0,7762.0,-4431.0,10107.0,104821.0,7518.0,2.355000e+02,104589.0,136295.0,5562.0,-12193.0,7736.0,52435.0,-2806.0,104589.0,107340.0,109020.0
1252,C_102,alive,2018,131339.0,152853.0,10903.0,81565.0,3956.0,59531.0,48995.0,1.073391e+06,265359.0,365725.0,93735.0,70662.0,112506.0,116866.0,66946.0,265359.0,258578.0,183794.0
1249,C_102,alive,2015,89378.0,129589.0,10500.0,81730.0,2349.0,53394.0,30343.0,6.153365e+05,233715.0,290479.0,53463.0,71230.0,104126.0,80610.0,91939.0,233715.0,171124.0,151985.0
1251,C_102,alive,2017,128645.0,131648.0,9400.0,70744.0,4855.0,48351.0,35673.0,7.900501e+05,229234.0,375319.0,97207.0,61344.0,97586.0,100814.0,98180.0,229234.0,241272.0,158490.0
1250,C_102,alive,2016,106869.0,121576.0,9800.0,69276.0,2132.0,45687.0,29299.0,6.032536e+05,215091.0,321686.0,75427.0,59476.0,93515.0,79006.0,96998.0,215091.0,193437.0,145815.0
6955,C_563,alive,2008,72266.0,329078.0,12379.0,78669.0,11646.0,45220.0,24702.0,3.972341e+05,425071.0,228052.0,7025.0,66290.0,95993.0,49100.0,255749.0,425071.0,110529.0,346402.0
6959,C_563,alive,2012,64460.0,339228.0,15888.0,65769.0,14542.0,44880.0,34987.0,3.896481e+05,420714.0,333795.0,7928.0,49881.0,81486.0,64139.0,353543.0,420714.0,162135.0,354945.0
1246,C_102,alive,2012,57653.0,84641.0,3205.0,58446.0,791.0,41733.0,18692.0,6.265504e+05,156508.0,176064.0,0.0,55241.0,71867.0,38542.0,101788.0,156508.0,57854.0,98062.0
6958,C_563,alive,2011,72963.0,346775.0,15583.0,69687.0,15024.0,41060.0,38642.0,4.012538e+05,433526.0,331052.0,9322.0,54104.0,86751.0,77505.0,321816.0,433526.0,170308.0,363839.0
6954,C_563,alive,2007,85963.0,272336.0,12250.0,69905.0,11089.0,40610.0,36450.0,5.042396e+05,358600.0,242082.0,7183.0,57655.0,86264.0,58312.0,230507.0,358600.0,116038.0,288695.0